### PR TITLE
fixed compiling error under Windows due to missing of a matching cons…

### PR DESCRIPTION
**Pull request by rockonedege**
there's actually one change at line# 255, somehow VS2015 reformatted the whole file.

### CODE REVIEW

**Comment by berkus** [comment]
Can you undo formatting changes? I cannot accept that as it is.

**Comment by rockonedege** [comment]
I just tried again.This seems to be a crlf thing. Although I changed only one line, the whole file changed to be windows style line ending automatically, and under Windows the diff tool only shows one line of change before&after committing. I'll  learn how to keep the ending under Windows, or may be you could change line#255 under Linux.

**Comment by berkus** [comment]
Ok, I will take a look at this.

**Comment by rockonedege** [comment]
I just had another look, the 2nd commit did undo the line ending changes in the previous one. It's the change I meant, no more, no less. Should be ready for you to check & accept  it.

**Comment by berkus** [comment]
Fixed and merged.

**Pull request closed without merging**
