### PR TITLE
- fixed issue [#21](https://github.com/berkus/dir_monitor/issues/21) …

### PR DESCRIPTION
**Pull request by rockonedege**
This is to replace the previous PR. I had a little problem with cherry-pick, so squashed the changes instead. 

Still learning git, let me know if there's any problem.

### CODE REVIEW

**Comment by berkus** [comment]
Couple of comments, please see if that can be addressed in this PR.

Looks very good in general.

**Comment by rockonedege** [comment]
Gents, changed as suggested. Please review it.

**Comment by berkus** [comment]
I think it boost code it's generally better to use boost smart pointers, since they are sometimes working around broken compilers.

By `std::unique_ptr` in review i just meant a smart pointer, not specifically C++ std one.

**Comment by rockonedege** [comment]
In this specific case, we are using a feature that's only available to [`std::unique_ptr::release()`](http://en.cppreference.com/w/cpp/memory/unique_ptr/release), which is not available in `boost::scoped_ptr()` [by design](http://www.boost.org/doc/libs/1_60_0/libs/smart_ptr/scoped_ptr.htm).
there's no `boost::make_scoped()` either.

I feel it's bad and confusion to mix boost and std smart pointers in a single file, hence the changes.

**Comment by sbelsky** [comment]
@berkus well i haven't more remarks, except of small :lipstick::lipstick:

**Comment by GamePad64** [comment]
> I feel it's bad and confusing to mix boost and std smart pointers in a single file
Then just replace all the boost code with std, like I did in linux inotify backend in #6. Smart pointers are pretty well implemented in both GCC and MSVC.

**Comment by rockonedege** [comment]
Yes, this is what I thought and did in this commit.

**Comment by berkus** [comment]
I'll make a cleanup sweep on the code and merge it in a couple of days, stay tuned.

Thanks for your help, all!

**Comment by berkus** [comment]
Merged manually via [8dc6646]

**Pull request closed without merging**
