### PR TITLE
Hotfix/correct stop on windows

### PR DESCRIPTION
**Pull request by sbelsky**
in the wake of #27

### CODE REVIEW

**Comment by berkus** [comment]
Thanks!

**Comment by sbelsky** [comment]
:) I think it is necessary to add windows-based CI.

**Comment by berkus** [comment]
You know any?

**Comment by sbelsky** [comment]
https://www.appveyor.com
Well-integrated with github.

**Comment by berkus** [comment]
I've added a build there, care to write `appveyor.yml` for it?

**Comment by sbelsky** [comment]
Ok, I've just wanted to offer the same. But your turn is clang on MacOS implementation. It must be very similar as for Windows and Linux.

**Comment by berkus** [comment]
Yep, I'm adding that.

**Pull request merged**
