### PR TITLE
fixes for issue #21

### PR DESCRIPTION
**Pull request by rockonedege**
see discussions under #21.

### CODE REVIEW

**Comment by berkus** [comment]
That's quite a lot of merges back and forth, could it be streamlined with a rebase?

**Comment by rockonedege** [comment]
I am a newbie in git, any good reference for me to grasp the rebase concept quickly?

**Comment by berkus** [comment]
Otherwise, throwing xcp through io_service looks good to me.

Do we need to save the exception in the variable or it could be bound to the closure only?

**Comment by berkus** [comment]
Here's a good one on rebase - https://matthew-brett.github.io/pydagogue/rebase_without_tears.html

**Comment by berkus** [comment]
You'll need to do more work to avoid the merges, ideally - tag your commit `something`, reset your master to origin and then just cherry-pick your commit from `something`. Create new branch for the PR though, because if you push more commits to master on your side now, it will change this PR as well, which you don't want.

**Comment by rockonedege** [comment]
according to what I learned,  to move an exception between thread,  the rethrow() is the only correct way.
we could transfer the exceptions from work_thread to io_service, but then there's no chance to rethow from io_service, as io_service::run() is blocking. there's no calling point. So exceptions have to be thrown from inside io_service::run().

**Comment by rockonedege** [comment]
OK, I'll learn and do the rebase later. In the mean time, you may review the general idea to see if it needs refining.  Time for bed now.

**Comment by sbelsky** [comment]
@berkus these changes may affect on contract between directory_monitor and its clients. what do you think about it? is it necessary to change something in non-windows implementations?

**Comment by berkus** [comment]
@sbelsky thanks for reviewing this!

**Comment by berkus** [comment]
Continued in #25

**Pull request closed without merging**
